#!/usr/bin/env python3
"""Embed lib/i18n_engine.js into lib/web_ui.py as the _I18N_SCRIPT constant.

The engine is appended right after the HTML_TEMPLATE definition and inserted
into both LOGIN_TEMPLATE and HTML_TEMPLATE before </body>. Re-runnable: an
existing embedded block (between the BEGIN/END markers) is stripped first, so
editing i18n_engine.js and re-running this script updates web_ui.py in place.

Usage:  python3 tools/build_i18n.py
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = os.path.join(ROOT, 'lib', 'web_ui.py')
ENGINE = os.path.join(ROOT, 'lib', 'i18n_engine.js')

BEGIN = '# === BEGIN i18n auto-embed (generated by tools/build_i18n.py) ==='
END = '# === END i18n auto-embed ==='

def main():
    src = open(WEB, encoding='utf-8').read()
    # Strip any previous embed block
    src = re.sub(r'\n*' + re.escape(BEGIN) + r'.*?' + re.escape(END) + r'\n?', '', src, flags=re.S)

    engine = open(ENGINE, encoding='utf-8').read()
    if '"""' in engine:
        sys.exit('ERROR: engine contains triple-double-quote; cannot embed safely.')
    for bad in ('{{', '{%', '{#'):
        if bad in engine:
            sys.exit('ERROR: engine contains Jinja-sensitive sequence %r; it would be '
                     'interpreted by the template renderer.' % bad)

    m = re.search(r"HTML_TEMPLATE\s*=\s*'''", src)
    if not m:
        sys.exit('ERROR: HTML_TEMPLATE assignment not found.')
    close = src.index("\n'''", m.end()) + len("\n'''")

    block = (
        '\n\n' + BEGIN + '\n'
        '_I18N_SCRIPT = r"""\n<script>\n' + engine + '\n</script>\n"""\n'
        "LOGIN_TEMPLATE = LOGIN_TEMPLATE.replace('</body>', _I18N_SCRIPT + '</body>')\n"
        "HTML_TEMPLATE = HTML_TEMPLATE.replace('</body>', _I18N_SCRIPT + '</body>')\n"
        + END + '\n'
    )
    out = src[:close] + block + src[close:]
    # Sanity: valid Python
    import ast; ast.parse(out)
    open(WEB, 'w', encoding='utf-8').write(out)
    print('Embedded i18n engine into lib/web_ui.py (%d bytes).' % len(out))

if __name__ == '__main__':
    main()
